[theme]
primaryColor = "#024D99"              # our blue
backgroundColor = "#024D99"           # our blue, background
secondaryBackgroundColor = "#FFFFFC"   #  entry box
textColor = "#E8C221"                 # text
