[theme]
primaryColor = "#024D99"              #  background?
backgroundColor = "#024D99"           #  background?
secondaryBackgroundColor = "#002742"   #  entry box
textColor = "#FFFFFF"                 # text

# black is #000000
# white is #FFFFFF
# blue is #024D99
# Naby blue is #002742
